capture_date: 2024-08-09T20:44:00-04:00
scanner_user: "New York University Digital Library Technology Services"
scanner_make: "Phase One"
scanner_model: "IQ3 100MP"
bitonal_resolution_dpi: 600
scanning_order: left-to-right
reading_order: left-to-right